# Generated by Django 4.0.2 on 2022-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='eOwns',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='eRead',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='jOwns',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='jRead',
            field=models.BooleanField(),
        ),
    ]
